### ISSUE TITLE
Is it possible to not generate the wizard bar?

### ISSUE THREAD

**Issue by jeff-h** [rstaib/jquery-steps#157]
Is it possible to _not_ generate the wizard bar (I think thats what it's called — the auto-generated DIV.steps at the top)?

As a quick fix, and to illustrate what I am hoping for, I added the following to my CSS:

``` css
#steps .steps {
  display: none;
  visibility: hidden;
}
```
