### ISSUE TITLE
[BUG] .wizard ul statement conflicts with text editor <ul> tags

### ISSUE THREAD

**Issue by meness** [rstaib/jquery-steps#190]
Hi,

**Problem:**
Following statement conflicts with text editor `<ul>` tags.

``` css
.wizard ul,.tabcontrol ul{list-style:none!important;padding:0;margin:0}
```

**Solution:**

``` css
.wizard ul[role="tablist"],.tabcontrol ul{list-style:none!important;padding:0;margin:0}
```

**Comment by adrian-e** [comment]
Beware of the ul used for the next and previous buttons (they have the "menu" role).
I have used:

``` css
.wizard ul[role="tablist"],
.wizard ul[role="menu"],
.tabcontrol ul
{
    list-style: none !important;
    padding: 0;
    margin: 0;
}

.wizard ul[role="tablist"] > li,
.wizard ul[role="menu"] > li,
.tabcontrol ul > li
{
    display: block;
    padding: 0;
}

```
